### ISSUE TITLE
Add option to retrieve sections directly from canvas 

### ISSUE THREAD

**Issue by katsanjib046** [IonMich/instructor_pilot#35]
Currently, sections are first synced from UF Schedule of Courses website by using UF API. It needs to be changed such that one can sync sections directly from Canvas. Basically, this will allow instructors using canvas from other Institutions to use this program and it will also allow us to syncing unofficial developmental courses.

**Comment by IonMich** [comment]
Extra logic that identifies `extra_resources` has been adding in the `sync_from_canvas` module and the Schedule of Courses is now just an extra resource. Closing for now, although we will need to improve the API in the future.
