### ISSUE TITLE
Upload canvas modal not updated after sync

### ISSUE THREAD

**Issue by katsanjib046** [IonMich/instructor_pilot#53]
After the users are synced with canvas, if we don't reload the page, the modal associated with upload to canvas button shows that the submissions don't have canvas ID.

**Comment by IonMich** [comment]
This should be fixed now. With the new behavior, a message appears for a couple of seconds, followed by a forced reload.

In the future, if we want to remove the force reload the following should be addressed first:
- the dataset associated with the submissions should be updated after any changes in the database that affect visible elements in the assignment detail page.
- the message in the upload-to-canvas modal should be re-rendered each time we open it or each time the submissions dataset changes.
