### ISSUE TITLE
Make it easier to identify unsynced submissions. Identify students whose enrollment state is concluded.

### ISSUE THREAD

**Issue by AnanthKandala** [IonMich/instructor_pilot#63]
-Currently, there is no easy way for the end user to identify which submissions were not synced. 
-The current version does not recognize the fact that a student is deemed as 'concluded' by canvas. The submissions of such students are left unsynced by the 'Sync Labeled Submissions from Canvas' button. 

Desirable functionality:
- The end user should be able to easily identify which submissions were not synced with canvas.
- Indicate to the end user if the submission is by a student whose enrollment status is 'concluded'. (the State[ ] parameter in https://canvas.instructure.com/doc/api/enrollments.html)

**Comment by IonMich** [comment]
fixed by the latest commit. Unsynced counter now toggles a modal with the list of submissions without a Canvas ID.
